(() => {
  const pairs = {
    '月刊':'Issues','历史归档':'Archive','平台目录':'Directory','变更记录':'Changelog','风险清单':'Risk list','使用提醒':'Safety','最新一期':'Latest issue','已发布':'Published','免费层':'Free tier','赠金':'Credits','打开本期':'Open issue','查看全部':'View all','月刊归档':'Monthly issues','即将更新':'Upcoming','尚未发布':'Not published','数据快照':'Data snapshot','优先采用官方来源':'Official sources preferred','每月更新':'Monthly update','免费模型 API':'Free AI Model APIs','免费模型 API 目录':'Free AI model API directory','2026 年 8 月':'August 2026','2026 年 9 月':'September 2026','基础快照':'Base snapshot','可测试':'Available','需核实':'Verify','暂不推荐':'Exclude','发布后更新':'Post-publication updates','4 项变化':'4 changes','新增免费模型':'New free model','已退役 · 07.30':'Retired · 07.30','Cerebras 免费层':'Cerebras free tier','已结束 · 08.17':'Ended · 08.17','Kimi 旧模型':'Kimi legacy models','下线 · 08.31':'Sunset · 08.31','新增 · 08.20':'New · 08.20','国家超算互联网':'National Supercomputing Network','额度和资格需确认':'Quota and eligibility require confirmation','腾讯混元':'Tencent Hunyuan','与原混元资源包分开计算':'Separate from the original shared resource pack','新计费机制':'New billing mechanism','旧每日 2000 次口径失效':'Old 2K/day quota retired','以官方限制页和控制台为准':'Use the official limits page and current console value','重点图表':'Visual index','8 月变化':'August signals','快速选择':'Quick picks','按用途选择':'Use case recommendations','平台目录 / 基础快照':'Directory / base snapshot','核查日期 · 08.24':'Last checked · 08.24','基础快照 · 08.19':'Base snapshot · 08.19','长期免费层':'Permanent tier','每日额度':'Daily quota','一次性赠金':'One-time credits','注册赠金':'Signup credit','每月额度':'Monthly credit','限时活动':'Limited campaign','资源包':'Resource pack','代金券':'Voucher','订阅附带额度':'Subscription credit','多模态免费':'Multimodal free','公测期免费':'Public beta','兼容 OpenAI 的免费 API':'Free compatible API','需核实或暂不推荐':'Verify or exclude','需核实 · 13 个':'Verify · 13','暂不推荐 · 17 个':'Exclude · 17','接入前提醒':'Before calling','确认实名和绑卡要求':'Check identity and card requirements','确认超额后的计费方式':'Check overage billing behavior','保护密钥，不提交敏感数据':'Keep keys and sensitive data out','免费层只用于原型和备用':'Treat free tiers as prototype capacity','重点模型':'Featured models','免费端点':'Free endpoints','动态':'Dynamic','动态列表':'Dynamic list','包含多种模态 · 需按模型确认限制':'Mixed modalities · verify model-level limits','已变化 · 需核实':'Changed · verify','旧每日额度口径失效 · 查看官方限制':'Old daily-quota wording retired · see official limits','额度较小':'Small allowance','速率限制':'Rate limits','适合原型':'Prototype use','每日 10,000 Neurons':'10,000 Neurons/day','每日 1000 次':'1K RPD','每日 20 次':'20 RPD','约 2 · 需实名':'≈ 2 · real-name','试用额度':'Trial credit','免费调用':'Free calls','新用户赠金':'New-user credits','赠金 + 循环额度':'Credits + rolling','赠金 + 免费模型':'Credits + free models','新计费机制':'New billing model','已变化 · 需核实':'Changed · verify','第 1 期 / 2026 年 8 月':'Issue 01 / August 2026','信息核查截至 2026.08.24':'Checked · 2026.08.24',
    'AI 大事件':'AI events','本月大事':'This month','上期验尸与本月变化':'Follow-ups & changes','9 项变化':'9 changes','10 条 · 多源交叉':'10 items · cross-checked','9 月变化':'September signals','新渠道与重点模型':'New & featured','9 月亮点':'September picks','需核实 · 16 个':'Verify · 16','暂不推荐 · 9 个':'Exclude · 9','风险清单 / 25':'Risk list / 25','大事件':'Events','新渠道':'New channels','2026 年 10 月':'October 2026','共 2 期':'2 issues published','月刊目录 / 第 2 期':'Issues / No. 02','第 2 期 / 2026 年 9 月':'Issue 02 / September 2026','核查日期 · 09.21':'Last checked · 09.21','23 可测试':'23 available','16 需核实':'16 verify','9 暂不推荐':'9 exclude','29 可测试':'29 available','13 需核实':'13 verify','17 暂不推荐':'17 exclude','已下线 · 08.31 如期':'Sunset · 08.31 as planned','转付费 · 09 月确认':'Paid tier · Sep confirmed','新增 · 每日 5500 万':'New · 55M tokens/day','加量 · 每模型 100 万':'Boosted · 1M per model','每日循环额度':'Daily rolling quota','8 款 4.x Flash 免费':'8 free 4.x Flash models',':free 模型 21 款':':free · 21 models','积分制公测':'Credit-based beta','资源包升级':'Upgraded resource pack','每日积分':'Daily credits','Lite 永久免费':'Lite free forever','限时试用':'Trial offer','红名单除名':'Off the red list','新增 AI 大事件':'New: AI events',
    '24 可测试':'24 available','15 需核实':'15 verify','需核实 · 15 个':'Verify · 15','核查日期 · 09.21 · 共 24 家':'Checked 09.21 · 24 platforms','6 家':'6','10 家':'10','上期验尸 + 本月变化 · 10 项':'Follow-ups + changes · 10',
    '循环额度':'Rolling quota','聚合平台':'Aggregators','注册赠金 / 试用':'Credits / trial','注册赠金 / 订阅附带':'Credits / subscription','限速':'Limits','期限':'Validity','门槛':'Access','变化':'Change','接口':'Interface','注意':'Note','量级':'Scale','本月图表':'This issue in charts','本期图表':'Issue charts','需核实 16 · 暂不推荐 9':'Verify 16 · Exclude 9','需核实 13 · 暂不推荐 17':'Verify 13 · Exclude 17','核查日期 · 09.21 · 共 23 家':'Checked 09.21 · 23 platforms','核查日期 · 08.24 · 共 29 家':'Checked 08.24 · 29 platforms','上期验尸 + 本月变化 · 9 项':'Follow-ups + changes · 9','本月政策变化 · 8 项':'Policy changes · 8','09.01 – 09.21 · 10 条':'09.01–09.21 · 10 items'
  };
  const reverse = Object.fromEntries(Object.entries(pairs).map(([zh,en]) => [en,zh]));
  let english = localStorage.getItem('amr-lang') === 'en';
  function walk(node, map) {
    if (node.nodeType === Node.TEXT_NODE) {
      const value = node.nodeValue.trim();
      if (map[value]) node.nodeValue = node.nodeValue.replace(value, map[value]);
    } else if (node.nodeType === Node.ELEMENT_NODE && !['SCRIPT','STYLE','CODE'].includes(node.tagName)) {
      [...node.childNodes].forEach(child => walk(child, map));
    }
  }
  function apply() { walk(document.body, english ? pairs : reverse); document.documentElement.lang = english ? 'en' : 'zh-CN'; const b=document.querySelector('[data-lang-toggle]'); if(b) b.textContent=english?'中文':'EN'; }
  function addToggle() { const header=document.querySelector('.site-header'); if(!header) return; const b=document.createElement('button'); b.className='lang-toggle'; b.dataset.langToggle=''; b.onclick=()=>{english=!english;localStorage.setItem('amr-lang',english?'en':'zh');location.reload()}; header.appendChild(b); }
  addToggle(); apply();
})();
